export const WEDDING = {
  groom: { name: '허재', role: '장남', parents: '허민수 · 이수연' },
  bride: { name: '오지희', role: '차녀', parents: '오정훈 · 박혜진' },
  dateISO: '2026-08-29T14:20:00+09:00',
  dateLabel: '2026년 8월 29일 토요일',
  timeLabel: '오후 2시 20분',
  venue: '더 링크 호텔',
  hall: '5층 화이트홀',
  address: '서울특별시 강남구 테헤란로 77길 12',
  accounts: {
    groom: [
      { who: '신랑 허재', bank: '국민은행', num: '123-45-6789-012' },
      { who: '혼주 허민수', bank: '신한은행', num: '110-234-567890' },
    ],
    bride: [
      { who: '신부 오지희', bank: '카카오뱅크', num: '3333-21-7654321' },
      { who: '혼주 오정훈', bank: '우리은행', num: '1002-345-678901' },
    ],
  },
};

export const THEMES = {
  lavender: {
    name: '모더니스트',
    bg: '#FFFFFF',
    paper: '#FFFFFF',
    coverBg: '#FFFFFF',
    ink: '#1F1F1F',
    muted: '#6E6E6E',
    line: '#DADADA',
    accent: '#8A8A8A',
    accentSoft: '#ECECEC',
    serif: '"Nanum Myeongjo", "Noto Serif KR", serif',
    sans: '"Pretendard", -apple-system, sans-serif',
    script: '"Parisienne", "Dancing Script", cursive',
  },
  rose: {
    name: '더스티 로즈',
    bg: '#FFFFFF',
    paper: '#FFFFFF',
    coverBg: '#FFFFFF',
    ink: '#3A2B28',
    muted: '#9C857B',
    line: '#EFE3DB',
    accent: '#B8756B',
    accentSoft: '#F6EAE2',
    serif: '"Nanum Myeongjo", "Noto Serif KR", serif',
    sans: '"Pretendard", -apple-system, sans-serif',
    script: '"Parisienne", "Dancing Script", cursive',
  },
  cream: {
    name: '샴페인 크림',
    bg: '#FFFFFF',
    paper: '#FFFFFF',
    coverBg: '#FFFFFF',
    ink: '#3A2E1C',
    muted: '#9C8863',
    line: '#EEE4CE',
    accent: '#A08254',
    accentSoft: '#F5EEDF',
    serif: '"Nanum Myeongjo", "Noto Serif KR", serif',
    sans: '"Pretendard", -apple-system, sans-serif',
    script: '"Parisienne", "Dancing Script", cursive',
  },
  sage: {
    name: '세이지 그린',
    bg: '#FFFFFF',
    paper: '#FFFFFF',
    coverBg: '#FFFFFF',
    ink: '#2E382B',
    muted: '#8A9183',
    line: '#DFE4D6',
    accent: '#7A8B6E',
    accentSoft: '#EFF1E7',
    serif: '"Nanum Myeongjo", "Noto Serif KR", serif',
    sans: '"Pretendard", -apple-system, sans-serif',
    script: '"Parisienne", "Dancing Script", cursive',
  },
};

export const FONT_SETS = {
  classic: {
    name: '명조 + 캘리',
    serif: '"Nanum Myeongjo", "Noto Serif KR", serif',
    sans: '"Pretendard", -apple-system, sans-serif',
    script: '"Parisienne", "Dancing Script", cursive',
  },
  modern: {
    name: '모던 고딕',
    serif: '"Gowun Batang", "Noto Serif KR", serif',
    sans: '"Pretendard", sans-serif',
    script: '"Dancing Script", cursive',
  },
  hand: {
    name: '손글씨 무드',
    serif: '"Gowun Dodum", serif',
    sans: '"Gowun Dodum", sans-serif',
    script: '"Caveat", "Dancing Script", cursive',
  },
};
