export const THEMES = {
  lavender: {
    name: '모더니스트',
    bg: '#FFFFFF',
    paper: '#FFFFFF',
    coverBg: '#FFFFFF',
    ink: '#1F1F1F',
    muted: '#6E6E6E',
    line: '#DADADA',
    accent: '#8A8A8A',
    accentSoft: '#ECECEC',
    serif: '"Cormorant Garamond", "Noto Serif KR", "Nanum Myeongjo", serif',
    sans: '"Pretendard", -apple-system, "Noto Sans KR", sans-serif',
    script: '"Cormorant Garamond", "Noto Serif KR", "Nanum Myeongjo", serif',
  },
  rose: {
    name: '더스티 로즈',
    bg: '#FFFFFF',
    paper: '#FFFFFF',
    coverBg: '#FFFFFF',
    ink: '#3A2B28',
    muted: '#9C857B',
    line: '#EFE3DB',
    accent: '#B8756B',
    accentSoft: '#F6EAE2',
    serif: '"Cormorant Garamond", "Noto Serif KR", "Nanum Myeongjo", serif',
    sans: '"Pretendard", -apple-system, "Noto Sans KR", sans-serif',
    script: '"Cormorant Garamond", "Noto Serif KR", "Nanum Myeongjo", serif',
  },
  cream: {
    name: '샴페인 크림',
    bg: '#FFFFFF',
    paper: '#FFFFFF',
    coverBg: '#FFFFFF',
    ink: '#3A2E1C',
    muted: '#9C8863',
    line: '#EEE4CE',
    accent: '#A08254',
    accentSoft: '#F5EEDF',
    serif: '"Cormorant Garamond", "Noto Serif KR", "Nanum Myeongjo", serif',
    sans: '"Pretendard", -apple-system, "Noto Sans KR", sans-serif',
    script: '"Cormorant Garamond", "Noto Serif KR", "Nanum Myeongjo", serif',
  },
  sage: {
    name: '세이지 그린',
    bg: '#FFFFFF',
    paper: '#FFFFFF',
    coverBg: '#FFFFFF',
    ink: '#2E382B',
    muted: '#8A9183',
    line: '#DFE4D6',
    accent: '#7A8B6E',
    accentSoft: '#EFF1E7',
    serif: '"Cormorant Garamond", "Noto Serif KR", "Nanum Myeongjo", serif',
    sans: '"Pretendard", -apple-system, "Noto Sans KR", sans-serif',
    script: '"Cormorant Garamond", "Noto Serif KR", "Nanum Myeongjo", serif',
  },
} as const;
