export const THEMES = {
  lavender: {
    name: '모더니스트',
    bg: '#FAFAFA',
    ink: '#3A3540',
    muted: '#8A8A8A',
    line: '#E6E0EC',
    accent: '#8E7AB8',
    accentSoft: '#EDE6F3',
    serif: '"Cormorant Garamond", "Noto Serif KR", "Nanum Myeongjo", serif',
    sans: '"Pretendard", -apple-system, "Noto Sans KR", sans-serif',
  },
  rose: {
    name: '더스티 로즈',
    bg: '#FAF6F4',
    ink: '#4A3A36',
    muted: '#8A7A75',
    line: '#E6D7D0',
    accent: '#B8857A',
    accentSoft: '#F3E4DF',
    serif: '"Cormorant Garamond", "Noto Serif KR", "Nanum Myeongjo", serif',
    sans: '"Pretendard", -apple-system, "Noto Sans KR", sans-serif',
  },
  cream: {
    name: '샴페인 크림',
    bg: '#FAF7F1',
    ink: '#3D3528',
    muted: '#8A7B62',
    line: '#E5DBC9',
    accent: '#B09D7C',
    accentSoft: '#EFE5D5',
    serif: '"Cormorant Garamond", "Noto Serif KR", "Nanum Myeongjo", serif',
    sans: '"Pretendard", -apple-system, "Noto Sans KR", sans-serif',
  },
  sage: {
    name: '세이지 그린',
    bg: '#F5F8F2',
    ink: '#3A4537',
    muted: '#7F8A78',
    line: '#D8E0CF',
    accent: '#7F9478',
    accentSoft: '#DCE2D4',
    serif: '"Cormorant Garamond", "Noto Serif KR", "Nanum Myeongjo", serif',
    sans: '"Pretendard", -apple-system, "Noto Sans KR", sans-serif',
  },
} as const;
